FROM python:3.12-slim

WORKDIR /app

# Add this line to install distutils and other essentials
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    python3-distutils \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8080"]