# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy Python dependencies
COPY requirements.txt .

# Install Python dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# COPY model.pth /app/model.pth

RUN apt-get update && apt-get install -y git git-lfs \
    && git lfs install \
    && git clone https://github.com/JunaidLimalia/bcdapp.git /app \
    && cd /app && git lfs pull

# Copy model, frontend and backend code
COPY . .

# Define frontend build folder (optional)
ENV FRONTEND_DIR=/app/frontend/build

# Expose port for Flask
EXPOSE 8080

# Start the app
CMD ["python", "app.py"]